# Generated by Django 4.1.7 on 2023-03-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=15)),
                ('carrera', models.CharField(choices=[('ingenieria', 'Ingeniería'), ('matematicas', 'Matemáticas'), ('fisica', 'Física')], max_length=50)),
            ],
        ),
    ]
