# Generated by Django 4.1.7 on 2023-03-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.CharField(max_length=15),
        ),
    ]
